
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 01 19:09:05 CDT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int Parentesis_b = 21;
  public static final int For = 9;
  public static final int Parentesis_a = 20;
  public static final int Suma = 11;
  public static final int Numero = 27;
  public static final int Op_booleano = 19;
  public static final int ERROR = 32;
  public static final int Identificador = 26;
  public static final int Comillas = 3;
  public static final int Llave_b = 23;
  public static final int Llave_a = 22;
  public static final int Op_relacional = 16;
  public static final int T_dato = 4;
  public static final int Met = 31;
  public static final int Main = 24;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int Division = 14;
  public static final int Op_incremento = 18;
  public static final int Op_atribucion = 17;
  public static final int Resta = 12;
  public static final int If = 6;
  public static final int Private = 28;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Punto = 25;
  public static final int Op_logico = 15;
  public static final int Class = 30;
  public static final int Public = 29;
  public static final int Igual = 10;
  public static final int While = 8;
  public static final int Multiplicacion = 13;
}

